# Generated by Django 6.0.1 on 2026-01-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoasignacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productoasignacion',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
