# Generated by Django 6.0.1 on 2026-01-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_asignacion', '0002_productoasignacion_activa_and_more'),
        ('productos', '0004_producto_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoasignacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='productos.producto'),
        ),
    ]
