# Generated by Django 6.0.1 on 2026-01-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='propiedad',
            field=models.CharField(choices=[('PROPIO', 'Propio'), ('PRESTADO', 'Prestado'), ('ALQUILADO', 'Alquilado')], default='PROPIO', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='uso',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_REPARACION', 'En reparación'), ('DADO_DE_BAJA', 'Dado de baja'), ('PRESTADO', 'Prestado')], default='DISPONIBLE', max_length=20),
        ),
    ]
