# Generated by Django 6.0.1 on 2026-01-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_propiedad_producto_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
